### ISSUE TITLE
collectors to enforce types

### ISSUE THREAD

**Issue by thdesy** [ALU-Schumacher/AUDITOR#1308]
Dear developers,

due to a misconfiguration of my htcondor collector, I wrote a string type data field into the components `jsonb`  field of the postgres.

I.e.,
```
components:
...
  - name: "MaxHosts"
    key: "MaxHosts"
  - name: "LastRemoteHost"
    key: "LastRemoteHost"
```

where `LastRemoteHost` is a char type class ad in Condor. Thus, a job's resulting component's `jsonb` field contained a string value.  When trying to send the metrics upstream with the APEL exporter, the APEL exporter throws an error due to a data type not being able to be casted into an integer.

Suggested behaviour/solution:
exporters should throw an error when encountering data types not applicable to the components etc `jsonb` internal schemata and exit gracefully without proceeding enabling the operator to notice the error
