### ISSUE TITLE
Slurm collector: Add more options to select jobs in sacct command

### ISSUE THREAD

**Issue by QuantumDancer** [ALU-Schumacher/AUDITOR#472]
When calling `sacct`, we currently can only select jobs based on the job state.

https://github.com/ALU-Schumacher/AUDITOR/blob/4115613f88eab542221b7907b7af22954ac024aa/collectors/slurm/src/sacctcaller.rs#L99-L112

To reduce the load on the slurm database, we should also provide the functionality to filter on additional fields, like the partition, user, group, and account.

Relevant lines of the current config look like this

```yaml
job_status:  # A list of acceptable job states
  - "completed"
  - "failed"
  - "node_fail"
  ```

I propose that we change the format of the config slightly, collecting all filter options in one section:

```yaml
job_filter:
  status:
    - "completed"
    - "failed"
    - "node_fail"
  partition:
    - "partition1"
    - "partition2"
  user:
    - "user1"
    - "user1"
  group:
    - "group1"
    - "group2"
  account:
    - "account1"
    - "account2"
```

The `status` filter should remain mandatory (as we always want to filter out pending and running jobs). The other filters should be optional.

The filters should then be translated to the corresponding options for the `sacct` command:

```
-r, --partition
          Comma separated list of partitions to select jobs and job steps from. The default is all partitions.
-A, --accounts=<account_list>
          Displays jobs when a comma separated list of accounts are given as the argument.
-u, --uid=, --user=<uid_or_user_list>
          Use this comma separated list of UIDs or user names to select jobs to display.  By default, the running user's UID is used.
-g, --gid=, --group=<gid_or_group_list>
          Displays the statistics only for the jobs started with the GID or the GROUP specified by the gid_list or the group_list operand, which is a comma-separated list.  Space characters are not allowed.  Default is no restrictions.
```
